workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set iOS deployment target to 13.0 (create or update Podfile)
        script: |
          cd ios
          if [ ! -f Podfile ]; then
            echo "Creating Podfile..."
            pod init
            sed -i '' "s/# platform :ios.*/platform :ios, '13.0'/" Podfile
          else
            echo "Updating Podfile..."
            sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" Podfile || echo "Setting platform line"
            grep -q "platform :ios, '13.0'" Podfile || echo "platform :ios, '13.0'" >> Podfile
          fi
          cd ..
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Generate localization files
        script: |
          flutter gen-l10n
      - name: Build for iOS simulator
        script: |
          flutter build ios --simulator --no-codesign
      - name: Zip the .app file
        script: |
          mkdir -p build/ios/ipa
          zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip

