workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies and generate localization
        script: |
          flutter pub get
          flutter gen-l10n
      - name: Build iOS Simulator App
        script: flutter build ios --simulator
      - name: Zip the .app file
        script: |
          mkdir -p build/ios/ipa
          zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip
