workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean and fetch packages
        script: |
          flutter clean
          flutter pub get
      - name: Set iOS deployment target and install CocoaPods
        script: |
          cd ios
          if [ ! -f Podfile ]; then
            pod init
          fi
          # Set platform to iOS 13
          sed -i '' "s/^#\? *platform :ios.*/platform :ios, '13.0'/" Podfile || echo "platform :ios, '13.0'" >> Podfile

          # Disable Bitcode (optional but helps with Firebase)
          echo "
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
              end
            end
          end
          " >> Podfile

          rm -rf Pods Podfile.lock
          pod install
          cd ..
      - name: Generate localization (optional)
        script: flutter gen-l10n
      - name: Build iOS release app
        script: flutter build ios --release
      - name: Export .ipa
        script: |
          mkdir -p build/ios/ipa
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/
    artifacts:
      - build/ios/ipa/**
