// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9287NvcBtVrbq6VsznwyNOig-hbLiYT0',
    appId: '1:552764090603:web:2712137e99455be09476ae',
    messagingSenderId: '552764090603',
    projectId: 'puzzle-2048-4e974',
    authDomain: 'puzzle-2048-4e974.firebaseapp.com',
    storageBucket: 'puzzle-2048-4e974.firebasestorage.app',
    measurementId: 'G-JTM5KKW5W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_3Hls0vs0N9t5XzN-jn6Hh4Q7Ag9sZCI',
    appId: '1:552764090603:android:b1935bbdf857ec939476ae',
    messagingSenderId: '552764090603',
    projectId: 'puzzle-2048-4e974',
    storageBucket: 'puzzle-2048-4e974.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8cS28Ax2k831Z_MK0wC4511IzWmU9NxM',
    appId: '1:552764090603:ios:6f8332e8428348a09476ae',
    messagingSenderId: '552764090603',
    projectId: 'puzzle-2048-4e974',
    storageBucket: 'puzzle-2048-4e974.firebasestorage.app',
    iosBundleId: 'com.example.game2048',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8cS28Ax2k831Z_MK0wC4511IzWmU9NxM',
    appId: '1:552764090603:ios:6f8332e8428348a09476ae',
    messagingSenderId: '552764090603',
    projectId: 'puzzle-2048-4e974',
    storageBucket: 'puzzle-2048-4e974.firebasestorage.app',
    iosBundleId: 'com.example.game2048',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9287NvcBtVrbq6VsznwyNOig-hbLiYT0',
    appId: '1:552764090603:web:78c9b18e9b49cbbf9476ae',
    messagingSenderId: '552764090603',
    projectId: 'puzzle-2048-4e974',
    authDomain: 'puzzle-2048-4e974.firebaseapp.com',
    storageBucket: 'puzzle-2048-4e974.firebasestorage.app',
    measurementId: 'G-DEFDW2NRXB',
  );

}